# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Candidate.create(name: "Donald John Trump", political_affiliation: "Republican", birth_date: "6/14/1946", experience: "President of Trump Organization", religion: "Presbyterianism", home_state: "New York", total_raised: "$1,902,410", summary: "Donald Trump is an American real estate developer, television personality, politician, and author. He is the chairman and president of The Trump Organization and the founder of Trump Entertainment Resorts. Trump's branding efforts, business career, outspoken manner, media appearances, and books have made him famous. He hosted The Apprentice and The Celebrity Apprentice, both U.S. television programs on NBC.", img_url: "")
Candidate.create(name: "John Ellis 'Jeb' Bush", political_affiliation: "Republican", birth_date: "2/11/1953", experience: "Former Governor of Florida", religion: "Roman Catholicism", home_state: "Florida", total_raised: "$119,929,898", summary: "Jeb Bush is an American businessman and politician who served as the 43rd Governor of Florida from 1999 to 2007. During his eight years as governor, Bush was credited with initiating environmental improvements, such as conservation in the Everglades, supporting caps for medical malpractice litigation, moving Medicaid recipients to private systems, and instituting reforms to the state education system, including the issuance of vouchers and promoting school choice.", img_url: "")
Candidate.create(name: "Benjamin Solomon 'Ben' Carson, Sr.", political_affiliation: "Republican", birth_date: "9/18/1951", experience: "Pediatric Neurosurgery", religion: "Seventh-day Adventist", home_state: "Maryland", total_raised: "$10,800,000", summary: "Ben Carson, Sr is an American author, political pundit, and retired Johns Hopkins neurosurgeon. Carson was the first surgeon to successfully separate conjoined twins joined at the head. In 2008, he was awarded the Presidential Medal of Freedom by President George W. Bush. On May 4, 2015, Carson announced he was running for the Republican nomination in the 2016 Presidential election at a rally in Detroit, his hometown.", img_url: "")
Candidate.create(name: "Marco Antonio Rubio", political_affiliation: "Republican", birth_date: "5/28/1971", experience: "U.S. Senator, Florida", religion: "Roman Catholicism", home_state: "Florida", total_raised: "$45,200,000", summary: "Marco Rubio is the junior United States Senator from Florida, serving since January 2011, and a candidate for President of the United States. A member of the Republican Party, he previously served as Speaker of the Florida House of Representatives. Rubio is one of three Latinos (all Cuban Americans) in the Senate, along with Bob Menendez of New Jersey and Ted Cruz of Texas.", img_url: "")
Candidate.create(name: "Rafael Edward 'Ted' Cruz", political_affiliation: "Republican", birth_date: "12/22/1970", experience: "U.S. Senator, Texas", religion: "Southern Baptist", home_state: "Texas", total_raised: "$52,400,000", summary: "Ted Cruz is the junior United States Senator from Texas. A Republican, Cruz was elected senator in 2012 and is the first Hispanic or Cuban American to serve as a U.S. Senator representing Texas.He is the chairman of the subcommittee on the Oversight, Agency Action, Federal Rights and Federal Courts, U.S. Senate Judiciary Committee. He is also the chairman of the United States Senate Commerce Subcommittee on Space, Science and Competitiveness, U.S. Senate Commerce Committee. On March 23, 2015, Cruz announced during a rally at Liberty University he would run for the Republican Party nomination in the 2016 U.S. Presidential election.", img_url: "")


Candidate.create(name: "Hillary Diane Rodham Clinton", political_affiliation: "Democratic", birth_date: "10/26/1947", experience: "Former U.S. Secretary of State", religion: "Methodism", home_state: "New York", total_raised: "$67,849,950", summary: "Hillary Clinton is an American politician and stateswoman who is a former first lady, former United States Secretary of State in the administration of President Barack Obama from 2009 to 2013, and former United States Senator representing New York from 2001 to 2009. As the wife of President Bill Clinton, she was First Lady of the United States from 1993 to 2001. Clinton unsuccessfully ran for the 2008 Democratic presidential nomination, and is currently running for the 2016 nomination.", img_url: "")
Candidate.create(name: "Bernard 'Bernie' Sanders", political_affiliation: "Democratic", birth_date: "9/8/1941", experience: "U.S. Senator, Vermont", religion: "Judaism", home_state: "Vermont", total_raised: "$15,247,353", summary: "Bernie Sanders is the junior United States Senator from Vermont. Sanders is the longest-serving independent in U.S. congressional history. A self-described democratic socialist, he favors policies similar to those of social democratic parties in Europe, particularly those instituted by the Nordic countries. He caucuses with the Democratic Party and has been the ranking minority member on the Senate Budget Committee since January 2015.", img_url: "")
Candidate.create(name: "Martin Joseph O'Malley", political_affiliation: "Democratic", birth_date: "1/18/1963", experience: "Former Governor of Maryland", religion: "Roman Catholicism", home_state: "Maryland", total_raised: "$2,606,905", summary: "Martin O'Malley was the 61st Governor of Maryland, from 2007 to 2015, and is running for President of the United States in the 2016 election. Prior to being elected as Governor, he served as the Mayor of Baltimore from 1999 to 2007 and was a Baltimore City Councilor from 1991 to 1999. O'Malley served as the Chair of the Democratic Governors Association from 2011 to 2013, while serving as governor of Maryland. Following his departure from public office in early 2015, he was appointed to the Johns Hopkins University's Carey Business School as a visiting professor focusing on government, business, and urban issues.", img_url: "")
Candidate.create(name: "James Henry 'Jim' Webb, Jr.", political_affiliation: "Democratic", birth_date: "2/9/1946", experience: "Former U.S. Senator, Virginia", religion: "Protestant", home_state: "Virginia", total_raised: "N/A", summary: "Jim Webb is an American politician and author. He has served as a United States Senator from Virginia, Secretary of the Navy, Assistant Secretary of Defense, Counsel for the House Veterans Affairs Committee, and Marine Corps officer. In the private sector, he has been an Emmy-award winning journalist, a filmmaker, and the author of ten books. In addition, he taught literature at the United States Naval Academy and was a Fellow at the Harvard Institute of Politics. As a member of the Democratic Party, Webb announced on November 19, 2014, that he was forming an exploratory committee to evaluate a run for President of the United States in 2016. On July 2, 2015, he announced that he would be joining the race for the Democratic nomination for President.", img_url: "")
Candidate.create(name: "Lincoln Davenport Chafee", political_affiliation: "Democratic", birth_date: "3/26/1953", experience: "Former Governor of Rhode Island", religion: "Episcopalian", home_state: "Rhode Island", total_raised: "$392,743", summary: "Lincoln Chafee is an American politician from Rhode Island who has served as the Mayor of Warwick (1993–1999), a U.S. Senator (1999–2007) and as the 74th Governor of Rhode Island (2011–2015). On April 9, 2015, Chafee announced that he was exploring a run for U.S. President as a Democrat in the 2016 election. Chafee formally announced the launch of his campaign on June 3, 2015.", img_url: "")

Issue.create(topic: "Gun control")
Issue.create(topic: "Drugs")
Issue.create(topic: "Abortion")
Issue.create(topic: "Immigration")
Issue.create(topic: "Civil Rights")




