# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#republican candidates
Candidate.create(name: "Donald John Trump", political_affiliation: "Republican", birth_date: "6/14/1946", experience: "President of Trump Organization", religion: "Presbyterianism", home_state: "New York", total_raised: "$1,902,410", summary: "Donald Trump is an American real estate developer, television personality, politician, and author. He is the chairman and president of The Trump Organization and the founder of Trump Entertainment Resorts. Trump's branding efforts, business career, outspoken manner, media appearances, and books have made him famous. He hosted The Apprentice and The Celebrity Apprentice, both U.S. television programs on NBC.", img_url: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Donald_Trump_August_19_2015.jpg")
Candidate.create(name: "John Ellis 'Jeb' Bush", political_affiliation: "Republican", birth_date: "2/11/1953", experience: "Former Governor of Florida", religion: "Roman Catholicism", home_state: "Florida", total_raised: "$119,929,898", summary: "Jeb Bush is an American businessman and politician who served as the 43rd Governor of Florida from 1999 to 2007. During his eight years as governor, Bush was credited with initiating environmental improvements, such as conservation in the Everglades, supporting caps for medical malpractice litigation, moving Medicaid recipients to private systems, and instituting reforms to the state education system, including the issuance of vouchers and promoting school choice.", img_url: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Governor_of_Florida_Jeb_Bush_at_Southern_Republican_Leadership_Conference_May_2015_by_Michael_Vadon_16.jpg")
Candidate.create(name: "Benjamin Solomon 'Ben' Carson, Sr.", political_affiliation: "Republican", birth_date: "9/18/1951", experience: "Pediatric Neurosurgery", religion: "Seventh-day Adventist", home_state: "Maryland", total_raised: "$10,800,000", summary: "Ben Carson, Sr is an American author, political pundit, and retired Johns Hopkins neurosurgeon. Carson was the first surgeon to successfully separate conjoined twins joined at the head. In 2008, he was awarded the Presidential Medal of Freedom by President George W. Bush. On May 4, 2015, Carson announced he was running for the Republican nomination in the 2016 Presidential election at a rally in Detroit, his hometown.", img_url: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Ben_Carson_at_CPAC_2015.jpg")
Candidate.create(name: "Marco Antonio Rubio", political_affiliation: "Republican", birth_date: "5/28/1971", experience: "U.S. Senator, Florida", religion: "Roman Catholicism", home_state: "Florida", total_raised: "$45,200,000", summary: "Marco Rubio is the junior United States Senator from Florida, serving since January 2011, and a candidate for President of the United States. A member of the Republican Party, he previously served as Speaker of the Florida House of Representatives. Rubio is one of three Latinos (all Cuban Americans) in the Senate, along with Bob Menendez of New Jersey and Ted Cruz of Texas.", img_url: "https://upload.wikimedia.org/wikipedia/commons/7/79/Marco_Rubio%2C_Official_Portrait%2C_112th_Congress.jpg")
Candidate.create(name: "Rafael Edward 'Ted' Cruz", political_affiliation: "Republican", birth_date: "12/22/1970", experience: "U.S. Senator, Texas", religion: "Southern Baptist", home_state: "Texas", total_raised: "$52,400,000", summary: "Ted Cruz is the junior United States Senator from Texas. A Republican, Cruz was elected senator in 2012 and is the first Hispanic or Cuban American to serve as a U.S. Senator representing Texas.He is the chairman of the subcommittee on the Oversight, Agency Action, Federal Rights and Federal Courts, U.S. Senate Judiciary Committee. He is also the chairman of the United States Senate Commerce Subcommittee on Space, Science and Competitiveness, U.S. Senate Commerce Committee. On March 23, 2015, Cruz announced during a rally at Liberty University he would run for the Republican Party nomination in the 2016 U.S. Presidential election.", img_url: "https://upload.wikimedia.org/wikipedia/commons/8/87/Ted_Cruz%2C_official_portrait%2C_113th_Congress.jpg")

#democratic candidates
Candidate.create(name: "Hillary Diane Rodham Clinton", political_affiliation: "Democratic", birth_date: "10/26/1947", experience: "Former U.S. Secretary of State", religion: "Methodism", home_state: "New York", total_raised: "$67,849,950", summary: "Hillary Clinton is an American politician and stateswoman who is a former first lady, former United States Secretary of State in the administration of President Barack Obama from 2009 to 2013, and former United States Senator representing New York from 2001 to 2009. As the wife of President Bill Clinton, she was First Lady of the United States from 1993 to 2001. Clinton unsuccessfully ran for the 2008 Democratic presidential nomination, and is currently running for the 2016 nomination.", img_url: "https://upload.wikimedia.org/wikipedia/commons/2/27/Hillary_Clinton_official_Secretary_of_State_portrait_crop.jpg")
Candidate.create(name: "Bernard 'Bernie' Sanders", political_affiliation: "Democratic", birth_date: "9/8/1941", experience: "U.S. Senator, Vermont", religion: "Judaism", home_state: "Vermont", total_raised: "$15,247,353", summary: "Bernie Sanders is the junior United States Senator from Vermont. Sanders is the longest-serving independent in U.S. congressional history. A self-described democratic socialist, he favors policies similar to those of social democratic parties in Europe, particularly those instituted by the Nordic countries. He caucuses with the Democratic Party and has been the ranking minority member on the Senate Budget Committee since January 2015.", img_url: "https://upload.wikimedia.org/wikipedia/commons/d/de/Bernie_Sanders.jpg")
Candidate.create(name: "Martin Joseph O'Malley", political_affiliation: "Democratic", birth_date: "1/18/1963", experience: "Former Governor of Maryland", religion: "Roman Catholicism", home_state: "Maryland", total_raised: "$2,606,905", summary: "Martin O'Malley was the 61st Governor of Maryland, from 2007 to 2015, and is running for President of the United States in the 2016 election. Prior to being elected as Governor, he served as the Mayor of Baltimore from 1999 to 2007 and was a Baltimore City Councilor from 1991 to 1999. O'Malley served as the Chair of the Democratic Governors Association from 2011 to 2013, while serving as governor of Maryland. Following his departure from public office in early 2015, he was appointed to the Johns Hopkins University's Carey Business School as a visiting professor focusing on government, business, and urban issues.", img_url: "https://upload.wikimedia.org/wikipedia/commons/3/37/Governor_O%27Malley_Portrait.jpg")
Candidate.create(name: "James Henry 'Jim' Webb, Jr.", political_affiliation: "Democratic", birth_date: "2/9/1946", experience: "Former U.S. Senator, Virginia", religion: "Protestant", home_state: "Virginia", total_raised: "N/A", summary: "Jim Webb is an American politician and author. He has served as a United States Senator from Virginia, Secretary of the Navy, Assistant Secretary of Defense, Counsel for the House Veterans Affairs Committee, and Marine Corps officer. In the private sector, he has been an Emmy-award winning journalist, a filmmaker, and the author of ten books. In addition, he taught literature at the United States Naval Academy and was a Fellow at the Harvard Institute of Politics. As a member of the Democratic Party, Webb announced on November 19, 2014, that he was forming an exploratory committee to evaluate a run for President of the United States in 2016. On July 2, 2015, he announced that he would be joining the race for the Democratic nomination for President.", img_url: "https://upload.wikimedia.org/wikipedia/commons/8/85/Jim_Webb_official_110th_Congress_photo.jpg")
Candidate.create(name: "Lincoln Davenport Chafee", political_affiliation: "Democratic", birth_date: "3/26/1953", experience: "Former Governor of Rhode Island", religion: "Episcopalian", home_state: "Rhode Island", total_raised: "$392,743", summary: "Lincoln Chafee is an American politician from Rhode Island who has served as the Mayor of Warwick (1993–1999), a U.S. Senator (1999–2007) and as the 74th Governor of Rhode Island (2011–2015). On April 9, 2015, Chafee announced that he was exploring a run for U.S. President as a Democrat in the 2016 election. Chafee formally announced the launch of his campaign on June 3, 2015.", img_url: "https://upload.wikimedia.org/wikipedia/commons/3/36/Lincoln_Chafee_official_portrait.jpg")

#issues
Issue.create(topic: "Gun control")
Issue.create(topic: "Drugs")
Issue.create(topic: "Abortion")
Issue.create(topic: "Immigration")
Issue.create(topic: "Civil Rights")

#candidateissue gun control
CandidateIssue.create(candidate: 1, issue: 1, position: ["A very strong person on the Second Amendment. (Jun 2015)", "I am against gun control. (Feb 2011)", "Dems and Reps are both wrong on guns. (Jul 2000)", "For assault weapon ban, waiting period, & background check. (Jul 2000)"])
CandidateIssue.create(candidate: 2, issue: 1, position: ["Stand-your-ground bill: Deadly force OK when threatened. (Dec 2009)", "Violent gun crime rate is down by more than 25%. (Jan 2002)", "Use a Gun and You’re Done. (Nov 2001)", "Concealed carry OK; supports instant background check. (Jul 1998)"])
CandidateIssue.create(candidate: 3, issue: 1, position: ["Law-abiding citizens have right to guns without registration. (Mar 2014)", "Extremely pro-2nd Amendment; never let anyone tamper with it. (Feb 2014)", "Semi-automatic weapons ok in countryside, but not cities. (Mar 2013)"])
CandidateIssue.create(candidate: 4, issue: 1, position: ["Oppose the United Nations' Arms Trade Treaty. (Sep 2013)", "New gun laws are ineffective, so don't pass them. (Apr 2013)", "Has a concealed weapon permit, but does not carry a weapon. (Apr 2013)", "Voted NO on banning high-capacity magazines of over 10 bullets. (Apr 2013)", "Deal with gun violence, but do it constitutionally. (Feb 2013)", "As Speaker, failed to push law allowing guns at work. (Jun 2012)", "Opposes restrictions on the right to bear arms. (Aug 2010)", "Rated B+ by the NRA, indicating a pro-gun rights voting record. (Aug 2010)", "2nd Amendment is a cornerstone of our democracy. (Feb 2010)"])
CandidateIssue.create(candidate: 5, issue: 1, position: ["Oppose the United Nations' Arms Trade Treaty. (Sep 2013)", "Voted NO on banning high-capacity magazines of over 10 bullets. (Apr 2013)", "Opposes restricting the Second Amendment. (Oct 2012)", "Opposes unreasonable and burdensome gun restrictions. (Jul 2011)"])
CandidateIssue.create(candidate: 6, issue: 1, position: ["Rein in idea that anybody can have a gun anywhere, anytime. (May 2014)", "2000: advocate for national gun registry; 2008: backed off. (May 2014)", "Balance lawful gun ownership & keeping guns from criminals. (Apr 2008)", "Give local police access to federal gun tracking info. (Apr 2008)", "Let states & cities determine local gun laws. (Apr 2008)", "Against illegal guns, crack down on illegal gun dealers. (Jan 2008)", "Backed off a national licensing registration plan on guns. (Jan 2008)", "Get assault weapons & guns off the street. (Jul 2007)", "Background check system could prevent Virginia Tech massacre. (Apr 2007)", "Congress’ failure at Littleton response inspired Senate run. (Nov 2003)", "Keep guns away from people who shouldn’t have them. (Sep 2000)", "Limit access to weapons; look for early warning signs. (Sep 2000)", "License and register all handgun sales. (Jun 2000)", "Tough gun control keeps guns out of wrong hands. (Jul 1999)", "Gun control protects our children. (Jul 1999)", "Don’t water down sensible gun control legislation. (Jul 1999)", "Lock up guns; store ammo separately. (Jun 1999)", "Ban kids’ unsupervised access to guns. (Jun 1999)", "Get weapons off the streets; zero tolerance for weapons. (Sep 1996)"])
CandidateIssue.create(candidate: 7, issue: 1, position: ["Mixed approach to gun control vs. gun rights. (Apr 2015)", "Voted YES on banning high-capacity magazines of over 10 bullets. (Apr 2013)", "Voted YES on allowing firearms in checked baggage on Amtrak trains. (Apr 2009)", "Voted YES on prohibiting foreign & UN aid that restricts US gun ownership. (Sep 2007)", "Voted YES on prohibiting product misuse lawsuits on gun manufacturers. (Oct 2005)", "Rated F by the NRA, indicating a pro-gun control voting record. (Dec 2003)", "Voted YES on prohibiting suing gunmakers & sellers for gun misuse. (Apr 2003)", "Voted NO on decreasing gun waiting period from 3 days to 1. (Jun 1999)"])
CandidateIssue.create(candidate: 8, issue: 1, position: ["Ban assault weapons, limit clip size, & require fingerprints. (May 2015)", "Further toughen the enforcement of our gun laws. (Feb 2011)", "Prevent unauthorized firearm use with 'smart gun' technology. (Aug 2000)", "Supports restrictions on the right to bear arms. (Aug 2010)"])
CandidateIssue.create(candidate: 9, issue: 1, position: ["Allow veterans to register unlicensed guns acquired abroad. (Jun 2011)", "Voted YES on allowing firearms in checked baggage on Amtrak trains. (Apr 2009)", "Dangerousness, not mental incompetence, limits gun rights. (Mar 2009)", "Voted YES on prohibiting foreign & UN aid that restricts US gun ownership. (Sep 2007)", "Ban gun registration & trigger lock law in Washington DC. (Mar 2007)
"])
CandidateIssue.create(candidate: 10, issue: 1, position: ["Common sense adherence to the Second Amendment. (Jun 2015)", "Voted NO on prohibiting lawsuits against gun manufacturers. (Jul 2005)", "Voted NO on banning lawsuits against gun manufacturers for gun violence. (Mar 2004)"])

#candidateissue drugs
CandidateIssue.create(candidate: 1, issue: 2, position: ["Legalize drugs and use tax revenue to fund drug education. (Apr 2011)", "Never drinks, smokes, nor does drugs. (Feb 2011)", "Fired Miss USA crown winner due to drug over-indulgence. (Dec 2006)", "Never touched drugs, nor alcohol, tobacco, or coffee. (Jul 2000)"])
CandidateIssue.create(candidate: 2, issue: 2, position: ["Smoked pot & drank alcohol in late 1960s high school. (Feb 2015)", "My high school drug use was 'stupid' and 'wrong'. (Feb 2015)", "No medical marijuana; it's just a guise toward legalization. (Aug 2014)", "Illegal drugs moving over US-Mexico border has intensified. (Mar 2013)", "Deploy military on both sides of the US-Mexican border. (Mar 2013)", "Funding to reduce teen substance abuse and tobacco use. (Mar 2004)", "Create a prescription drug tracking system to prevent abuse. (Mar 2004)", "Opposed treatment instead of jail for nonviolent drug users. (Sep 2002)", "Mandatory prison sentences for drug offenses. (Nov 2001)", "More federal funding for all aspects of Drug War. (Aug 2000)", "Reduce drug use by 50% by prevention & enforcement. (Jul 1999)"])
CandidateIssue.create(candidate: 3, issue: 2, position: ["Marijuana for medical use, but not for recreational use. (Jan 2014)", "Religion kept me away from 1960s sex and drugs. (Jan 2012)", "Reducing blood alcohol limit to .02 reduces drunk driving. (Jan 2012)"])
CandidateIssue.create(candidate: 4, issue: 2, position: ["No responsible way to recreationally use marijuana. (May 2015)", "Legalizing would be a mistake; reduce sentences carefully. (Apr 2015)", "There is no responsible way to recreationally use marijuana. (May 2014)", "Enforce federal laws even where states have legalized pot. (May 2014)", "1987: Brother-in-law imprisoned for drug conviction. (Jun 2012)", "1986: brother-in-law's drug bust unexamined until 2011. (Jun 2012)", "Teach students skills to avoid gangs, violence, & drugs. (Nov 2006)"])
CandidateIssue.create(candidate: 5, issue: 2, position: ["Lower minimums and mandatory sentencing for drugs. (Apr 2015)"])
CandidateIssue.create(candidate: 6, issue: 2, position: ["More drug diversion; more community policing. (Apr 2015)", "Medical marijuana now; wait-and-see on recreational pot. (Jul 2014)", "Medical marijuana maybe ok; states decide recreational use. (Jun 2014)", "Reduce sentencing disparity for crack, but not retroactively. (Dec 2007)", "Require chemical resellers to certify against meth use. (Sep 2007)", "1969: held herself aloof from college drug counterculture. (Jul 2007)", "Divert non-violent drug offenders away from prison. (Jun 2007)", "End harsher sentencing for crack vs. powder cocaine. (Jun 2007)", "Gov. Clinton implicated in his brother Roger’s drug arrest. (Feb 2004)", "Address drug problem with treatment and special drug courts. (Oct 2000)", "Ambiguous reports of 1960s college alcohol & drug use. (Aug 1999)", "Involved parents most influential in reducing teen drug use. (Sep 1996)"])
CandidateIssue.create(candidate: 7, issue: 2, position: ["Exempt industrial hemp from marijuana laws. (Mar 2013)", "Exclude industrial hemp from definition of marijuana. (Aug 2012)", "Voted NO on military border patrols to battle drugs & terrorism. (Sep 2001)", "Legalize medical marijuana. (Jul 2001)", "Voted NO on subjecting federal employees to random drug tests. (Sep 1998)"])
CandidateIssue.create(candidate: 8, issue: 2, position: ["Executive Order to address this heroin epidemic. (Feb 2015)", "Proportionality in marijuana arrests, but not legalization. (Jan 2014)", "Let Colorado experiment with legalization, not Maryland. (Jan 2014)", "Baltimore recovered from open-air drug markets. (Nov 2013)"])
CandidateIssue.create(candidate: 9, issue: 2, position: ["Suggested earlier this week that he supports decriminalizing drug use (Aug 2015)"])
CandidateIssue.create(candidate: 10, issue: 2, position: ["Decriminalized small amounts of marijuana as governor. (Jun 2015)", "I doubt our culture would allow legalizing hard drugs. (Apr 2008)", "I doubt our culture would allow legalizing hard drugs. (Apr 2008)"])

#candidate issue abortion
CandidateIssue.create(candidate: 1, issue: 3, position: ["I have evolved on abortion issue, like Reagan evolved. (Aug 2015)", "Ban late abortions; exceptions for rape, incest or health. (Jun 2015)", "I am now pro-life; after years of being pro-choice. (Apr 2011)", "I changed my views to pro-life based on personal stories. (Apr 2011)", "I am pro-life; fight ObamaCare abortion funding. (Feb 2011)", "Pro-choice, but ban partial birth abortion. (Jul 2000)", "Favors abortion rights but respects opposition. (Dec 1999)"])
CandidateIssue.create(candidate: 2, issue: 3, position: ["Husband of Terri Schiavo blames Bush for harassment. (Jan 2015)", "Terri Schiavo case: ordered feeding tube reinserted. (Feb 2014)", "OpEd: Jeb avoids extremism on women's issues. (Aug 2012)", "Funded adoption counseling, but not abortion counseling. (Dec 2009)", "Prevent use of public funds for stem cell research. (Dec 2009)", "Created divisive 'Choose Life' license plates. (Feb 2007)", "Parental consent; clinic regulation; pro-life counseling. (Feb 2007)", "Restrict abortions to incest, rape, & health. (Jul 1998)", "No need to teach about abortion if we have moral absolutes. (Nov 1995)"])
CandidateIssue.create(candidate: 3, issue: 3, position: ["Ban abortion more than 20 weeks after fertilization. (May 2015)", "No abortion for convenience. (Jan 2014)", "The thought of abortion for convenience is repugnant. (Jan 2014)", "Persuaded mother of hydrocephalic baby to cancel abortion. (Jan 2012)"])
CandidateIssue.create(candidate: 4, issue: 3, position: ["Barbarians of our age have murdered millions of the unborn. (Aug 2015)", "Ban abortion after 20 weeks. (Apr 2015)", "Consensus that life begins at conception; so no abortion. (May 2014)", "I believe in protecting life but I'm not a chauvinist. (Mar 2013)", "Pro-life, but understands that woman's right is the law. (Jun 2012)", "Expand birth control exemption for faith-based organizations. (Jun 2012)", "Opposed Sotomayor nomination based on her Roe support. (Jun 2012)", "No right to privacy, that resulted in the Roe v. Wade. (Feb 2010)", "Require ultrasounds before performing abortions. (Feb 2010)", "Voted against funding stem cell research. (Apr 2006)", "Opposes both federal abortion funding & judicial activism. (Aug 2010)", "Supports prohibiting human embryonic stem cell research. (Aug 2010)", "Supports giving legal protection to unborn children. (Sep 2010)", "Prohibit federal funding for abortion. (May 2011)"])
CandidateIssue.create(candidate: 5, issue: 3, position: ["Allow vote to end Planned Parenthood's funding. (Aug 2015)", "Prosecute Planned Parenthood for criminal violations. (Aug 2015)", "Ban taxpayer funding of abortion & partial birth abortion. (Mar 2015)", "Companies can deny insuring birth control. (Apr 2012)", "Opposes public abortion funding. (Oct 2012)", "Opposes churches providing birth control. (Oct 2012)", "Protect innocent human life with partial-birth ban. (Jul 2011)"])
CandidateIssue.create(candidate: 6, issue: 3, position: ["Make abortion rare by supporting adoption & foster care. (Apr 2008)", "Potential for life begins at conception, but don’t intrude. (Apr 2008)", "Opposed China’s forced abortion & Romania’s forced pregnancy. (Apr 2008)", "Long-held moderate stance focuses on reducing abortions. (Mar 2008)", "Consistently uses Dem. Party line, 'safe, legal, and rare'. (Mar 2008)", "1974: pro-choice fervency not based on any personal abortion. (Jul 2007)", "1999: keep abortion safe, legal & rare into next century. (Jul 2007)", "Lift ban on stem cell research to cure devastating diseases. (Jun 2007)", "1993:Early action on abortion rights ended Right’s dominance. (Jun 2007)", "Personally would never abort; but deeply values choice. (Jun 2007)", "Abortion is a sad, tragic choice to many women. (May 2007)", "Respect Roe v. Wade, but make adoptions easier too. (Nov 2006)", "Partial birth exceptions for life-threatening abnormalities. (Apr 2006)", "Government should have no role in abortion decision. (Oct 2005)", "We can find common ground on abortion issue. (Sep 2005)", "Alternatives to pro-choice like forced pregnancy in Romania. (Nov 2003)", "Must safeguard constitutional rights, including choice. (Oct 2000)", "Late term abortion only if life or health are at risk. (Oct 2000)", "Remain vigilant on a woman’s right to chose. (Jan 2000)", "Keep abortion safe, legal and rare. (Jan 1999)", "Being pro-choice is not being pro-abortion. (Jan 1999)", "Reach out to teens to reduce teen sex problems. (Jan 1999)"])
CandidateIssue.create(candidate: 7, issue: 3, position: ["Ban anti-abortion limitations on abortion services. (Nov 2013)", "Require pharmacies to fulfill contraceptive prescriptions. (Jul 2011)", "Focus on preventing pregnancy, plus emergency contraception. (Jan 2009)", "Voted NO on prohibiting minors crossing state lines for abortion. (Mar 2008)", "Voted NO on barring HHS grants to organizations that perform abortions. (Oct 2007)", "Voted YES on expanding research to more embryonic stem cell lines. (Apr 2007)", "Provide emergency contraception at military facilities. (Apr 2007)", "Ensure access to and funding for contraception. (Feb 2007)", "Rated 0% by the NRLC, indicating a pro-choice stance. (Dec 2006)", "Emergency contraception for rape victims at all hospitals. (Sep 2006)", "Voted YES on allowing human embryonic stem cell research. (May 2005)", "Voted NO on restricting interstate transport of minors to get abortions. (Apr 2005)", "Voted NO on making it a crime to harm a fetus during another crime. (Feb 2004)", "Rated 100% by NARAL, indicating a pro-choice voting record. (Dec 2003)", "Voted NO on banning partial-birth abortion except to save mother’s life. (Oct 2003)", "Voted YES on forbidding human cloning for reproduction & medical research. (Feb 2003)", "Voted NO on funding for health providers who don't provide abortion info. (Sep 2002)", "Voted NO on banning Family Planning funding in US aid abroad. (May 2001)", "Voted NO on banning partial-birth abortions. (Apr 2000)", "Voted NO on barring transporting minors to get an abortion. (Jun 1999)", "Women have the right to choose, regardless of income. (Jun 1997)", "Protect the reproductive rights of women. (Jan 1993)"])
CandidateIssue.create(candidate: 8, issue: 3, position: ["Abortions should be legal, without government restriction. (May 2015)", "$101M for stem cell research over six years. (Feb 2012)", "Supports federal abortion funding. (Aug 2010)"])
CandidateIssue.create(candidate: 9, issue: 3, position: ["Voted NO on restricting UN funding for population control policies. (Mar 2009)", "Voted NO on defining unborn child as eligible for SCHIP. (Mar 2008)", "Voted NO on prohibiting minors crossing state lines for abortion. (Mar 2008)", "Voted NO on barring HHS grants to organizations that perform abortions. (Oct 2007)", "Voted YES on expanding research to more embryonic stem cell lines. (Apr 2007)", "Supports Roe v. Wade and abortion rights. (Jun 2006)"])
CandidateIssue.create(candidate: 10, issue: 3, position: ["Support right to woman's personal reproductive decisions. (Jun 2015)", "A woman should make her own reproductive decisions. (Sep 2012)", "Emotional & divisive abortion debate takes over other issues. (Apr 2008)", "Opposed Alito because he didn't respect right to privacy. (Apr 2008)", "Embryonic stem cell research could help with many diseases. (Sep 2006)", "Leaving abortion to states means only wealthy have choice. (Sep 2006)", "Sponsored bill for emergency contraception for rape victims. (Sep 2006)", "The real potential for cures is in the embryonic stem cells. (Aug 2006)", "Voted NO on notifying parents of minors who get out-of-state abortions. (Jul 2006)", "Expand embryonic stem cell research. (Jun 2004)", "Voted YES on $100M to reduce teen pregnancy by education & contraceptives. (Mar 2005)", "Voted NO on criminal penalty for harming unborn fetus during other crime. (Mar 2004)", "Rated 90% by NARAL, indicating a pro-choice voting record. (Dec 2003)", "Voted NO on banning partial birth abortions except for maternal life. (Mar 2003)", "Voted NO on maintaining ban on Military Base Abortions. (Jun 2000)"])

#candidateissues immigration
CandidateIssue.create(candidate: 1, issue: 4, position: ["We need wall on Mexican border, but ok to have a door in it. (Aug 2015)", "Mexican government is sending criminals across the border. (Aug 2015)", "Half of the undocumented residents in America are criminals. (Jun 2015)", "Mexico & Latin America send us drugs, crime, and rapists. (Jun 2015)", "Build great wall on southern border; have Mexico pay for it. (Jun 2015)", "We need strong borders; we need a wall. (Feb 2015)", "Citizenship for illegal immigrants is a GOP suicide mission. (Mar 2013)", "351,000 illegal aliens are in our prisons; costing $1.1B. (Dec 2011)", "Anchor babies were NEVER the intent of the 14th Amendment. (Dec 2011)", "Invite foreigners graduating from college to stay in US. (Dec 2011)", "Triple-layered fence & Predator drones on Mexican border. (Dec 2011)", "Control borders; even legal immigration should be difficult. (Jul 2000)", "Limit new immigration; focus on people already here. (Dec 1999)"])
CandidateIssue.create(candidate: 2, issue: 4, position: ["OpEd: Vigorously booed as moderate, by deep conservatives. (Aug 2015)", "Eliminate sanctuary cities, plus more enforcement. (Aug 2015)", "Earned legal status, not amnesty. (Aug 2015)", "There is no plan to deport 11 million people. (Feb 2015)", "2009: favored deportation; 2012: favored path to citizenship. (Feb 2015)", "Supports DREAM Act, but not via executive action. (Feb 2015)", "Immigrants are an engine of economic vitality. (Jan 2015)", "OpEd: Disagrees with Tea Party on immigration and education. (Dec 2014)", "OpEd: Rational sympathy rather than economic logic. (Apr 2014)", "Immigrants are committed to family, even if illegally here. (Apr 2014)", "Advocate for residency for illegal immigrants. (Mar 2014)", "My plan is legalization, not self-deportation. (Mar 2013)", "People come illegally because there's no legal path to come. (Mar 2013)", "Path to citizenship or path to legalization: both could work. (Mar 2013)", "Reform must make it easier to come legally than illegally. (Mar 2013)", "6-part proposal for comprehensive immigration reform. (Mar 2013)", "There is no realistic pathway to citizenship for most people. (Mar 2013)", "Objections to more multiracial America are misplaced. (Mar 2013)", "GOP wooed Hispanics in 2004; but alienated them by 2012. (Jun 2012)", "Pray for Comprehensive Immigration Reform, not AZ law. (Apr 2010)", "Speaks Spanish; husband and father of Hispanics. (Feb 2007)", "Share costs of legal immigration between states & federal. (Feb 2001)", "Federal government should deal with criminal repatriation. (Feb 2001)", "Import farm workers from Mexico. (Sep 2001)"])
CandidateIssue.create(candidate: 3, issue: 4, position: ["Moral low road to use cheap labor if no path to citizenship. (Feb 2015)", "Pathway to citizenship unfair to past & current immigrants. (Feb 2015)", "Use Canadian model for guest worker program. (Jan 2015)", "Common-sense solutions: guest workers plus harsher penalties. (Jan 2015)", "Overwhelming majority want the southern border secured. (Jan 2012)", "Deportation is moral low road; create guest worker program. (Jan 2012)"])
CandidateIssue.create(candidate: 4, issue: 4, position: ["Legal immigrants have been waiting in line for 15 years. (Aug 2015)", "Deal with border & future immigrants BEFORE any amnesty. (Feb 2015)", "Modernize immigration to win global competition for talent. (Sep 2014)", "Human trafficking law & deferred action caused border crisis. (Aug 2014)", "Give kids of illegal immigrants in-state tuition rates. (Jan 2014)", "Border control: 90% apprehension and 100% surveillance. (Apr 2013)", "Green cards after 10 years; secure border; & e-Verify. (Apr 2013)", "Compare reform to existing situation of 11 million illegals. (Apr 2013)", "Immigration is a human issue AND a law & order issue. (Mar 2013)", "Leave immigration to feds; 50 sets of laws is worse. (Jun 2012)", "English is de facto official language; let's recognize that. (Jun 2012)", "AZ anti-immigrant law demands papers like 'police state'. (Jun 2012)", "OpEd: Claimed falsely that parents fled Castro in 1959. (Jun 2012)", "Legal status, but not citizenship, to migrant's children. (Jun 2012)", "GOP DREAM Act: visas for going to college or military. (Apr 2012)", "AZ law may unreasonably single out some citizens. (Apr 2010)", "Don't count illegal immigrants in the 2010 census. (Apr 2010)", "Allow children of illegals to pay in-state college tuition. (Mar 2010)", "No amnesty in any form, not even back-of-the-line. (Mar 2010)", "Oppose amnesty in any reform. (Feb 2010)", "Opposes granting amnesty to illegal immigrants. (Sep 2010)", "Supports full implementation of current border security laws. (Sep 2010)"])
CandidateIssue.create(candidate: 5, issue: 4, position: ["Support Kate's Law: oppose our leaders who won't enforce. (Aug 2015)", "Path to citizenship is profoundly unfair to legal immigrants. (Feb 2015)", "End Obama's illegal amnesty via Congress' checks & balances. (Nov 2014)", "Defund amnesty; and refuse any nominees until rescinded. (Nov 2014)", "No path to citizenship for 1.65 million illegals in Texas. (Oct 2012)", "Give police more power to ask about immigration status. (Jun 2012)", "Boots on the ground, plus a wall. (Apr 2012)", "Triple the size of the Border Patrol. (Mar 2012)", "Strengthen border security and increase enforcement. (Jul 2011)"])
CandidateIssue.create(candidate: 6, issue: 4, position: ["Rein in idea that anybody can have a gun anywhere, anytime. (May 2014)", "2000: advocate for national gun registry; 2008: backed off. (May 2014)", "Balance lawful gun ownership & keeping guns from criminals. (Apr 2008)", "Give local police access to federal gun tracking info. (Apr 2008)", "Let states & cities determine local gun laws. (Apr 2008)", "Against illegal guns, crack down on illegal gun dealers. (Jan 2008)", "Backed off a national licensing registration plan on guns. (Jan 2008)", "Get assault weapons & guns off the street. (Jul 2007)", "Background check system could prevent Virginia Tech massacre. (Apr 2007)", "Congress’ failure at Littleton response inspired Senate run. (Nov 2003)", "Keep guns away from people who shouldn’t have them. (Sep 2000)", "Limit access to weapons; look for early warning signs. (Sep 2000)", "License and register all handgun sales. (Jun 2000)", "Tough gun control keeps guns out of wrong hands. (Jul 1999)", "Gun control protects our children. (Jul 1999)", "Don’t water down sensible gun control legislation. (Jul 1999)", "Lock up guns; store ammo separately. (Jun 1999)", "Ban kids’ unsupervised access to guns. (Jun 1999)", "Get weapons off the streets; zero tolerance for weapons. (Sep 1996)"])
CandidateIssue.create(candidate: 7, issue: 4, position: ["Mixed approach to gun control vs. gun rights. (Apr 2015)", "Voted YES on banning high-capacity magazines of over 10 bullets. (Apr 2013)", "Voted YES on allowing firearms in checked baggage on Amtrak trains. (Apr 2009)", "Voted YES on prohibiting foreign & UN aid that restricts US gun ownership. (Sep 2007)", "Voted YES on prohibiting product misuse lawsuits on gun manufacturers. (Oct 2005)", "Rated F by the NRA, indicating a pro-gun control voting record. (Dec 2003)", "Voted YES on prohibiting suing gunmakers & sellers for gun misuse. (Apr 2003)", "Voted NO on decreasing gun waiting period from 3 days to 1. (Jun 1999)"])
CandidateIssue.create(candidate: 8, issue: 4, position: ["Ban assault weapons, limit clip size, & require fingerprints. (May 2015)", "Further toughen the enforcement of our gun laws. (Feb 2011)", "Prevent unauthorized firearm use with 'smart gun' technology. (Aug 2000)", "Supports restrictions on the right to bear arms. (Aug 2010)"])
CandidateIssue.create(candidate: 9, issue: 4, position: ["Allow veterans to register unlicensed guns acquired abroad. (Jun 2011)", "Voted YES on allowing firearms in checked baggage on Amtrak trains. (Apr 2009)", "Dangerousness, not mental incompetence, limits gun rights. (Mar 2009)", "Voted YES on prohibiting foreign & UN aid that restricts US gun ownership. (Sep 2007)", "Ban gun registration & trigger lock law in Washington DC. (Mar 2007)"])
CandidateIssue.create(candidate: 10, issue: 4, position: ["Common sense adherence to the Second Amendment. (Jun 2015)", "Voted NO on prohibiting lawsuits against gun manufacturers. (Jul 2005)", "Voted NO on banning lawsuits against gun manufacturers for gun violence. (Mar 2004)"])

#candidateissue civil rights
CandidateIssue.create(candidate: 1, issue: 5, position: ["Disinvited from RedState gathering for misogynistic comments. (Aug 2015)", "Political correctness is country's problem, not my problem. (Aug 2015)", "Same-sex marriage is a state issue. (Jun 2015)", "No gay marriage; no same-sex partner benefits. (Mar 2011)", "Tolerate diversity; prosecute hate crimes against gays. (Jul 2000)"])
CandidateIssue.create(candidate: 2, issue: 5, position: ["OpEd: 'One Florida' scrapped affirmative action. (Apr 2015)", "Let businesses express religious freedom against gays. (Mar 2015)", "Respect civil unions & same-sex lifetime commitments. (Jan 2015)", "1994: LGBT protections are tantamount to elevating sodomy. (Jan 2015)", "Don't-ask-don't-tell ok if it doesn't affect policy. (Dec 2014)", "Traditional marriage best; but recognize gay couples. (Mar 2013)", "Replaced affirmative action with 'One Florida' initiative. (Jun 2012)", "Insisted on more racial and gender diversity in trial judges. (Mar 2008)", "Dismantled Florida's affirmative action program. (Feb 2007)", "One Florida: equal minority contracts and admissions. (Feb 2007)", "Don't create gays as another category of victims. (Feb 2007)", "Removed Confederate battle flag from Florida Capitol. (Feb 2007)", "1981: Left Houston based on prejudice against Mexican wife. (Sep 2004)", "Support principles embodied in the Equal Rights Amendment. (Feb 2001)", "Provide licensure exams in Spanish, for free. (Jun 2000)", "Supports Affirmative Action; against quotas. (Jul 1998)", "No hate-crimes status for gays; no gay marriage. (Jul 1998)", "Gay rights & feminism are 'modern victim movements'. (Nov 1995)"])
CandidateIssue.create(candidate: 3, issue: 5, position: ["Homosexuality is a choice, but same-sex marriage is the law. (May 2015)", "Give gays rights, but not marriage, because it's a choice. (Mar 2015)", "Don't let the PC police label conservatives as extremists. (Feb 2015)", "Underdog status is not determined any longer by race. (Feb 2014)", "Apologized for likening homosexuality to pedophilia. (Mar 2013)", "Marriage should not be extended to same-sex couples. (Mar 2013)", "1960s: experienced racism in inner-city Boston and Detroit. (Jan 2012)", "Reparations for WWII Japanese ok, but not for slavery. (Jan 2012)", "Not all black candidates share Obama's left-wing politics. (Jan 2012)", "Redefining marriage is slippery slope with disastrous ending. (Jan 2012)", "Legal binding relationship for gays to enjoy property rights. (Jan 2012)", "Legal binding relationship for gays to enjoy property rights. (Jan 2012)"])
CandidateIssue.create(candidate: 4, issue: 5, position: ["One-man-one-woman marriage existed before our laws. (Apr 2015)", "I oppose gay marriage, but it's the law of the land. (Apr 2015)", "Opposes Paycheck Fairness: don't require equal pay for women. (Apr 2014)", "Balance gay anti-discrimination with religious rights. (Mar 2014)", "Defining marriage does not demean a class of people. (Jun 2013)", "I believe in historical marriage, but ok if states redefine. (Jun 2013)", "Leave gay marriage to states, but keep DOMA. (Mar 2013)", "Voted NO on reauthorizing the Violence Against Women Act. (Feb 2013)", "Supports Amendment to prevent same sex marriage. (Aug 2010)", "Opposes Employment Non-Discrimination Act (ENDA). (Sep 2010)"])
CandidateIssue.create(candidate: 5, issue: 5, position: ["Pray against a court decision legalizing same-sex marriage. (Apr 2015)", "Liberals obsessed with mandatory gay marriage in 50 states. (Apr 2015)", "Zealotry on same-sex marriage leaves out religious liberty. (Apr 2015)", "Most states can ignore Supreme Court legalizing gay marriage. (Mar 2015)", "Overturn Supreme Court with anti-gay marriage Amendment. (Oct 2014)", "Sponsored state definition of marriage supersedes federal gay marriage. (Feb 2014)", "Opposes gay pride parades and opposes gay marriage. (Feb 2012)", "One-man-one-woman marriage is building block of society. (Jul 2011)", "Disallow Ku Klux Klan from participating in Adopt-A-Highway. (Jul 2011)"])
CandidateIssue.create(candidate: 6, issue: 5, position: ["I re-evaluated & changed my mind on gay marriage. (Jun 2014)", "We have all evolved on gay marriage since 1990s. (Jun 2014)", "DOMA discrimination holds us back from a more perfect union. (Jun 2013)", "I support gay marriage personally and as law. (Mar 2013)", "Telling kids about gay couples is parental discretion. (Sep 2007)", "Positive about civil unions, with full equality of benefits. (Aug 2007)", "Let states decide gay marriage; they’re ahead of feds. (Aug 2007)", "GLBT progress since 2000, when I marched in gay pride parade. (Aug 2007)", "Supports DOMA, which Bill Clinton signed. (Jul 2007)", "Don’t ask don’t tell was an important transition step. (Jun 2007)", "2004:defended traditional marriage; 2006:voted for same-sex. (May 2007)", "Federal Marriage Amendment would be terrible step backwards. (Oct 2006)", "Gay soldiers need to shoot straight, not be straight. (Nov 2003)", "End hate crimes and other intolerance. (Sep 2000)", "Gays deserve domestic partnership benefits. (Feb 2000)", "Military service based on conduct, not sexual orientation. (Dec 1999)"])
CandidateIssue.create(candidate: 7, issue: 5, position: ["Equal pay for equal work by women. (Mar 2015)", "Enforce against anti-gay discrimination in public schools. (Jun 2013)", "Voted YES on reauthorizing the Violence Against Women Act. (Feb 2013)", "Enforce against wage discrimination based on gender. (Jan 2013)", "Endorsed as 'preferred' by The Feminist Majority indicating pro-women's rights. (Aug 2012)", "Prohibit sexual-identity discrimination at schools. (Mar 2011)", "ENDA: prohibit employment discrimination for gays. (Jun 2009)", "Recognize Juneteenth as historical end of slavery. (Jun 2008)", "Re-introduce the Equal Rights Amendment. (Mar 2007)", "Rated 97% by the NAACP, indicating a pro-affirmative-action stance. (Dec 2006)", "Rated 100% by the HRC, indicating a pro-gay-rights stance. (Dec 2006)", "Voted NO on Constitutionally defining marriage as one-man-one-woman. (Jul 2006)", "Bush’s tracking citizens’ phone call patterns is illegal. (Jun 2006)", "Voted NO on making the PATRIOT Act permanent. (Dec 2005)", "Voted NO on Constitutional Amendment banning same-sex marriage. (Sep 2004)", "Voted NO on protecting the Pledge of Allegiance. (Sep 2004)", "Voted NO on constitutional amendment prohibiting flag desecration. (Jun 2003)", "Rated 93% by the ACLU, indicating a pro-civil rights voting record. (Dec 2002)", "Constitutional Amendment for equal rights by gender. (Mar 2001)", "Voted NO on banning gay adoptions in DC. (Jul 1999)", "Voted NO on ending preferential treatment by race in college admissions. (May 1998)", "Never accept racism, sexism, nor homophobia. (Jun 1997)", "1964: civil rights activist in Congress on Racial Equality. (Jun 1997)"])
CandidateIssue.create(candidate: 8, issue: 5, position: ["All are created equal, including gay, lesbian & transgender. (May 2015)", "Led Maryland to 2012 same-sex marriage law. (Apr 2015)", "Respect dignity of individuals & support same-sex marriage. (Jan 2014)", "Civil marriage rights for all Marylanders. (Feb 2012)", "Shift from group preferences to economic empowerment of all. (Aug 2000)", "Opposes Amendment to prevent same sex marriage. (Aug 2010)"])
CandidateIssue.create(candidate: 9, issue: 5, position: ["Evolution on gay marriage has been good for the country. (Oct 2014)", "ENDA: prohibit employment discrimination for gays. (Jun 2009)", "Affirmative action should apply to African-Americans only. (Sep 2006)", "Supports civil unions; opposes constitutional ban. (Jun 2006)", "Opposes constitutional ban of gay marriage. (Jun 2006)", "Government’s power should end at my front door. (Apr 2006)", "Realign politics by union of Scots-Irish & African Americans. (Jan 2006)"])
CandidateIssue.create(candidate: 10, issue: 5, position: ["People of color are the future of Rhode Island. (Jan 2014)", "Longtime supporter of the LGBTQ community. (Nov 2010)", "1964: Opposing Civil Rights Act was wrong side of history. (Apr 2008)", "2006: Marriage Amendment ignores states' rights. (Apr 2008)", "Gay marriage is a state issue, not for federal constitution. (Sep 2006)", "Voted NO on recommending Constitutional ban on flag desecration. (Jun 2006)", "Voted NO on constitutional ban of same-sex marriage. (Jun 2006)", "Voted YES on adding sexual orientation to definition of hate crimes. (Jun 2002)", "Require 90 day delay for compliance before ADA lawsuits. (May 2002)", "Limit interstate class-action lawsuits to federal courts. (May 2002)", "Rated 60% by the ACLU, indicating a mixed civil rights voting record. (Dec 2002)", "Voted YES on loosening restrictions on cell phone wiretapping. (Oct 2001)", "Supports “Sexual orientation protected by civil rights laws”. (Sep 2000)", "Voted YES on expanding hate crimes to include sexual orientation. (Jun 2000)", "Continue affirmative action programs. (Jan 2000)"])

